### ISSUE TITLE
Pre-commit Checklist

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#12]
- [x] - Readme.txt validates?
- [x] - Screenshots match readme
- [x] - Screenshots correct mime type
- [x] - Version numbers match (readme and plugin)

**Comment by mpsparrow** [comment]
I am closing this as it seems like everything on it is complete.
