### ISSUE TITLE
Release 5.3

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#79]
#### Enhancements
- [x] Dashboard Wireframe #76 
- [x] Dashboard Styling #78 
- [x] Dashboard Coding #77 
- [x] Dashboard Tab View (General) #53
#### Documentation
- [x] Update Assets (screenshots mostly) #71
- [x] Redo parts in the GitHub Wiki #75 
- [x] Update information for the readme.txt description #75 
- [x] Add contributor props where appropriate (plugin page, description, and/or in the help tab) #81 
#### Translations
- [x] Update German and Formal German Translations #72 
- [x] Update POT Translation #80 
#### Testing
- [x] Test on Single Site #82 
- [x] Test on Multisite #82 
- [x] Test on Mobile Devices (iPad, iPhone, Android Device, Blackberry Device, etc.) #82 
#### Pre Commit Checklist
- [x] Bump version number in plugin files
- [x] Add readme.txt changelog

**Comment by mpsparrow** [comment]
So when should we plan to release 5.3?

**Comment by mpsparrow** [comment]
or rather what should the roadmap be for 5.3 since it is a bigger version?

**Comment by ronalfy** [comment]
Main first task is wireframe. Then hrml. Then CSS. Then behavior (JavaScript).

**Comment by ronalfy** [comment]
Let's not set a release date until I talk to my designer friend.?

**Comment by mpsparrow** [comment]
Sounds good! I can add your designer friend to have committing rights when we are ready.

On the other hand I will be more then happy to take on the documentation for the project (i.e. wiki updating, screenshots, readme.txt, etc.).

**Comment by ronalfy** [comment]
Cool. He'd like a .org add if he contributes.

**Comment by ronalfy** [comment]
I imagine he'll do the wireframe and CSS.

**Comment by mpsparrow** [comment]
What is his .org profile?

**Comment by ronalfy** [comment]
I need to talk to him first. He seemed interested, but need to give him a tour of what we neeed. Let's check back sometime next week.

**Comment by mpsparrow** [comment]
sounds good

**Comment by mpsparrow** [comment]
Just updated the To Do list above to add more information.

**Comment by ronalfy** [comment]
Good work!

**Comment by mpsparrow** [comment]
Thanks. Thought a clearer more details to do list was a good idea for a big release.

**Comment by mpsparrow** [comment]
Now a ticket is added for everything on the to do list. That way this issue doesn't get junked up with endless discussions.

**Comment by mpsparrow** [comment]
Should we update the video tutorials for 5.3?

**Comment by ronalfy** [comment]
Yes, but right now it's a nice to have. They take quite a while to do.

**Comment by mpsparrow** [comment]
Ok, then I won't bother. As long as we update the screenshots and documentation it should be good.

**Comment by ronalfy** [comment]
I'll do do it. Let's not place on critical path like we did for 5.0.

**Comment by ronalfy** [comment]
Let's get this out today if we can. Even if it isn't perfect. Can always make it better.

**Comment by mpsparrow** [comment]
Ok, I will do some testing myself along with clean up some documentation. Then we can release it this evening.
